### ISSUE TITLE
Profession Endpoint returns additional weapon skills for at least Guardian

### ISSUE THREAD

**Issue by Linkaaaaa** [HardstuckGuild/GW2-API-Issues#6]
Tested on multiple characters and builds, same behaviour:

![7363](https://github.com/HardstuckGuild/GW2-Tooltips.js/assets/23245218/451d42e5-8e8d-439e-af70-e6a871278aad)

![7364](https://github.com/HardstuckGuild/GW2-Tooltips.js/assets/23245218/ead9d2e4-b849-474c-9233-c88e56a9c4ad)

**Comment by SaculRennorb** [comment]
I assume this is specific to guardian staff and does not happen with other weapons or professions?

**Comment by Linkaaaaa** [comment]
Yes necro staff works fine, was about to post the build code as example but my power went out lol

**Comment by SaculRennorb** [comment]
Ok, so I've pinned it down to a problem with the HS API and will move the issue there.
