### ISSUE TITLE
"text all" endpoint returns 500

### ISSUE THREAD

**Issue by Northburns** [HardstuckGuild/GW2-API-Issues#9]
# How To Reproduce
1. Send a request to <https://gw2-api.hardstuck.gg/text/all>
2. Server responds with 500 and text "internal server error"

**Comment by SaculRennorb** [comment]
Ok so i looked into this for a bit now, and unfortunately this is a massive case of "works on my machine". As you pointed out you hit this almost every time on the server, but I'm completely unable to reproduce it locally. It has to do with serializing broken strings, so it shouldnt affect normal usage, but for this specific EP we almost always hit a case like that.
